//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class User
    {
        [Required(ErrorMessage ="Không để trống UserName")]
        [StringLength(50,ErrorMessage ="Dài Quá Má")]
        public string Username { get; set; }


        [Required(ErrorMessage = "Không để trống Password")]
        [StringLength(50, ErrorMessage = "Dài Quá Má")]

        public string Password { get; set; }


        [MinLength(5,ErrorMessage ="Nhập đầy đủ Họ và Tên")]

        [Required(ErrorMessage = "Không để trống Họ và Tên")]

        [StringLength(50, ErrorMessage = "Dài Quá Má")]
        public string Name { get; set; }


        public Nullable<System.DateTime> Birthday { get; set; }

        [Required(ErrorMessage = "Không để trống SĐT")]
        [StringLength(10, ErrorMessage = "SĐT Việt Nam nha")]
        public string Phone { get; set; }


        [Required(ErrorMessage = "Không để trống Địa chỉ")]
        public string Address { get; set; }
    }
}
