//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
        [Required(ErrorMessage = "Không được để trống")]
        [MinLength(5, ErrorMessage = "Tối thiểu 5 kí tự")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [MinLength(5, ErrorMessage = "Tối thiểu 5 kí tự")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [MinLength(5, ErrorMessage = "Tối thiểu 5 kí tự")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public Nullable<System.DateTime> Birthday { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        [MaxLength(10, ErrorMessage = "10 số")]
        [MinLength(10, ErrorMessage = "10 số")]
        [Phone]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        public string Address { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public string avatar { get; set; }

        [Required(ErrorMessage = "Không được để trống")]
        [EmailAddress]
        public string Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
